#!/bin/bash
# Script to commit and push generated Astoria map files to git
# This runs after update_progress.py generates new map data

# Don't use set -e here - we need to handle errors manually for better control

echo "📦 Committing updated Astoria map files..."

# Navigate to project root (from /opt/render/project/src/backend/app/scripts/astoria to /opt/render/project/src)
cd /opt/render/project/src || {
    echo "❌ Error: Could not navigate to project root"
    exit 1
}

# Verify we're in a git repository
if [ ! -d .git ]; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Ensure we're on main branch (Render may checkout in detached HEAD)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" = "HEAD" ]; then
    echo "📍 Detected detached HEAD, switching to main branch..."
    git checkout main || {
        echo "❌ Error: Could not checkout main branch"
        exit 1
    }
fi

# Configure git for automated commits
git config user.name "Astoria Conquest Bot"
git config user.email "astoria-bot@camilomartinez.co"

# Stash any uncommitted changes (like test_render_workflow.sh) before pulling
git stash --include-untracked --quiet 2>/dev/null || true

# Pull latest changes from remote FIRST (before committing) to avoid conflicts
echo "📥 Pulling latest changes from remote..."
if ! git pull --rebase origin main 2>/dev/null; then
    # If rebase fails, try regular merge
    echo "⚠️  Rebase failed, trying merge..."
    if ! git pull --no-rebase origin main 2>/dev/null; then
        echo "⚠️  Pull failed, but continuing with local changes..."
    fi
fi

# Restore stashed changes (our generated files should be here)
# If there are conflicts, we want our generated files (theirs in stash context) to win
if ! git stash pop --quiet 2>/dev/null; then
    # If stash pop had conflicts, resolve them by keeping our generated files
    echo "⚠️  Stash pop had conflicts, resolving by keeping generated files..."
    git checkout --theirs public/data/astoria-conquest/astoria-progress-stats.json 2>/dev/null || true
    git checkout --theirs public/data/astoria-conquest/astoria-covered-streets.geojson 2>/dev/null || true
    git checkout --theirs public/data/astoria-conquest/astoria-base-map.geojson 2>/dev/null || true
    git add public/data/astoria-conquest/*.json public/data/astoria-conquest/*.geojson 2>/dev/null || true
    # Drop the stash since we've manually resolved
    git stash drop --quiet 2>/dev/null || true
fi

# Check if there are changes to commit
if git diff --quiet public/data/astoria-conquest/; then
    echo "✅ No changes to commit - map data is up to date"
    exit 0
fi

# Add the generated files
git add public/data/astoria-conquest/astoria-covered-streets.geojson
git add public/data/astoria-conquest/astoria-progress-stats.json
git add public/data/astoria-conquest/astoria-base-map.geojson

# Create commit with timestamp
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
git commit -m "chore: update Astoria Conquest map data - ${TIMESTAMP}

Automatically generated by Render cron job.
- Updated covered streets
- Updated progress stats
- Refreshed base map" || {
    echo "❌ Error: Failed to create commit"
    exit 1
}


# Push to main branch
echo "📤 Pushing to GitHub..."
if git push origin main; then
    echo "✅ Successfully pushed updated map data to GitHub"
    echo "🚀 Vercel will auto-deploy with the new data"
else
    echo "❌ Error: Failed to push to GitHub"
    exit 1
fi
