#!/bin/bash
# Script to commit and push generated Astoria map files to git
# This runs after update_progress.py generates new map data

set -e  # Exit on error

echo "📦 Committing updated Astoria map files..."

# Navigate to project root (from /opt/render/project/src/backend/app/scripts/astoria to /opt/render/project/src)
cd /opt/render/project/src

# Verify we're in a git repository
if [ ! -d .git ]; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Ensure we're on main branch (Render may checkout in detached HEAD)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" = "HEAD" ]; then
    echo "📍 Detected detached HEAD, switching to main branch..."
    git checkout main
fi

# Configure git for automated commits
git config user.name "Astoria Conquest Bot"
git config user.email "astoria-bot@camilomartinez.co"

# Check if there are changes to commit
if git diff --quiet public/data/astoria-conquest/; then
    echo "✅ No changes to commit - map data is up to date"
    exit 0
fi

# Add the generated files
git add public/data/astoria-conquest/astoria-covered-streets.geojson
git add public/data/astoria-conquest/astoria-progress-stats.json
git add public/data/astoria-conquest/astoria-base-map.geojson

# Create commit with timestamp
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
git commit -m "chore: update Astoria Conquest map data - ${TIMESTAMP}

Automatically generated by Render cron job.
- Updated covered streets
- Updated progress stats
- Refreshed base map"

# Pull latest changes from remote (in case of concurrent runs)
echo "📥 Pulling latest changes from remote..."
git pull --rebase origin main || {
    echo "⚠️  Pull failed, attempting to resolve..."
    # If pull fails due to conflicts, prefer our changes
    git rebase --abort 2>/dev/null || true
    git pull --strategy-option=ours origin main || true
}

# Push to main branch
echo "📤 Pushing to GitHub..."
git push origin main

echo "✅ Successfully pushed updated map data to GitHub"
echo "🚀 Vercel will auto-deploy with the new data"
